version: '3'
services:
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    ports:
      - 5432:5432

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: josued@mail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - 5050:80

  books-service:
    image: d4vecode/examen:1.0.0
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres-sql:5432/distribuida
    depends_on:
      - postgres-sql
    deploy:
      replicas: 1
    ports:
      - 7001:7001

  # Si existe mas de una replica no se pone el puerto porque no puede apuntar al mismo puerto
#    ports:
#      - "7001:7001"