create table if not exists public.authors
(
    id integer generated by default as identity primary key,
    first_name   varchar(40),
    last_name varchar(40)
);
ALTER TABLE IF EXISTS public.books
    ADD FOREIGN KEY (author_id)
    REFERENCES public.authors (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;