create table if not exists public.books
(
    id integer generated by default as identity primary key,
    isbn   varchar(16),
    author_id integer,
    price  numeric(6, 2),
    title  varchar(128)
);
